#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GPA_Calculator.Resource", IsApplication=true)]

namespace GPA_Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int grade_letters = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gpa = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gpaCalc = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gpaShow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Help = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int UJ = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060035
			public const int CumGPA_btn = 2131099701;
			
			// aapt resource value: 0x7f060003
			public const int ViewCumGPA_btn = 2131099651;
			
			// aapt resource value: 0x7f060029
			public const int calculate_btn = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int clear_btn = 2131099690;
			
			// aapt resource value: 0x7f06000c
			public const int course1_textView = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int course2_textView = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int course3_textView = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int course4_textView = 2131099672;
			
			// aapt resource value: 0x7f06001c
			public const int course5_textView = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int course6_textView = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int course7_textView = 2131099684;
			
			// aapt resource value: 0x7f060007
			public const int course_textview = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int credit1_textView = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int credit2_textView = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int credit3_textView = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int credit4_textView = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int credit5_textView = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int credit6_textView = 2131099681;
			
			// aapt resource value: 0x7f060025
			public const int credit7_textView = 2131099685;
			
			// aapt resource value: 0x7f060008
			public const int credit_textview = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int display_CumGPA = 2131099652;
			
			// aapt resource value: 0x7f06002c
			public const int gpaDisplay_textView = 2131099692;
			
			// aapt resource value: 0x7f060037
			public const int gpaRecordView = 2131099703;
			
			// aapt resource value: 0x7f060034
			public const int gpa_btn = 2131099700;
			
			// aapt resource value: 0x7f060009
			public const int grade_textView = 2131099657;
			
			// aapt resource value: 0x7f060033
			public const int help_btn = 2131099699;
			
			// aapt resource value: 0x7f060030
			public const int help_textView = 2131099696;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f06002d
			public const int record_btn = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int semester = 2131099694;
			
			// aapt resource value: 0x7f060001
			public const int space1 = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int spinner1 = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int spinner2 = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int spinner3 = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int spinner4 = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int spinner5 = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int spinner6 = 2131099682;
			
			// aapt resource value: 0x7f060026
			public const int spinner7 = 2131099686;
			
			// aapt resource value: 0x7f060005
			public const int tableLayout1 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int tableLayout2 = 2131099658;
			
			// aapt resource value: 0x7f060027
			public const int tableLayout3 = 2131099687;
			
			// aapt resource value: 0x7f060006
			public const int tableRow1 = 2131099654;
			
			// aapt resource value: 0x7f06002b
			public const int tableRow10 = 2131099691;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow2 = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow3 = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int tableRow4 = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int tableRow5 = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int tableRow6 = 2131099675;
			
			// aapt resource value: 0x7f06001f
			public const int tableRow7 = 2131099679;
			
			// aapt resource value: 0x7f060023
			public const int tableRow8 = 2131099683;
			
			// aapt resource value: 0x7f060028
			public const int tableRow9 = 2131099688;
			
			// aapt resource value: 0x7f06002f
			public const int textView = 2131099695;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060031
			public const int textView3 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int uj_logo = 2131099698;
			
			// aapt resource value: 0x7f060036
			public const int viewCumgpa_btn = 2131099702;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CumulativeGPA = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CurrentGPA = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Help = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewGPAs = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int grade_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
